# Generated by Django 5.0.6 on 2024-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='posts.post'),
        ),
    ]
